import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import ReduxProvider from "@/providers/ReduxProvider";

import "../globals.css";
import { Suspense } from "react";
import AuthProvider from "../AuthGuard";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <Suspense fallback={null}>
            
            <AuthProvider>
          {children}

            </AuthProvider>
        
         
           
          </Suspense>
        </ReduxProvider>
      </body>
    </html>
  );
}

